<?php

$title = 'My Posts';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><a href="<?php echo $this->url('blog', array(
        'action'=>'add'));?>">Add new Post</a></p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Status</th>
    <th>Tags</th>
    <th>Content</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($posts as $post) : ?>
<tr>
    <td><?php echo $this->escapeHtml($post->title);?></td>
     <td><?php echo $this->escapeHtml($post->status);?></td>
     <td><?php echo $this->escapeHtml($post->tags);?></td>
    <td><?php echo $this->escapeHtml($post->content);?></td>    <td>
        <a href="<?php echo $this->url('blog',
            array('action'=>'edit', 'id' => $post->id));?>">Edit</a>
        <a href="<?php echo $this->url('blog',
            array('action'=>'delete', 'id' => $post->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
